# ===================================================================
# springboot标准配置
# ===================================================================
spring:
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    ROOT: INFO
    com.longfor: INFO
    com.longfor.longjian: debug
    graphql.GraphQL: debug


management:
  security:
    enabled: false
  info:
    git:
      enabled: true
    env:
      enabled: true
endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
  info:
    enabled: true
    sensitive: false